version: "3"

volumes:
  postgres:

services:
  quarkus:
    image: quarkus/getting-started-jvm
    container_name: app
    environment:
      JAVA_ENABLE_DEBUG: "true"
    ports:
      - "8080:8080"
      - "5005:5005"
    network_mode: "host"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: user
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "15432:5432"
    networks:
      - env-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  sonar:
    image: sonarqube
    container_name: sonar
    ports:
    - "9000:9000"
    networks:
      - env-network
networks:
  env-network:
    driver: bridge
